#!/bin/bash
#Script to compile and execute Java programs, for VazzupOJ
#First argument - FileName
#Second argument - Input file
echo "Compiling program..."
javac ./res/programs/$1.java
echo "Compiled successfully..."
echo "Executing program..."
if [-z "$2"] && [-z "$3"]; then
	java -cp ./res/programs/ $1
else
	java -cp ./res/programs/ $1 <./res/testcases/$2.in >./res/testcases/$2.test.out
	python3 compare.py $2
fi
rm ./res/programs/*.class
rm ./res/testcases/$2.test.out
echo "Executed successfully"
