#!/bin/bash
#Script to compile and execute Java programs, for VazzupOJ
#First argument - FileName
#Second argument - input file
#third argument - output file
echo "Compiling program..."
javac ./res/programs/$1.java
echo "Compiled successfully..."
echo "Executing program..."
java -cp ./res/programs/ $1
echo "Executed successfully"